version: "3.8"
services:
   server1:
      image: thandriss/minichain
      container_name: server1
      command: java -jar /minichain/Minichain-0.0.1.jar -p 8080 -n server3:8082,server2:8081 -f
      ports:
         - 8080:8080
   server2:
      image: thandriss/minichain
      container_name: server2
      command: java -jar /minichain/Minichain-0.0.1.jar -p 8081 -n server1:8080,server3:8082
      ports:
         - 8081:8081
   server3:
      image: thandriss/minichain
      container_name: server3
      command: java -jar /minichain/Minichain-0.0.1.jar -p 8082 -n server1:8080,server2:8081
      ports:
         - 8082:8082


